### PR TITLE
Tests: numthreads to 1

### PR DESCRIPTION
**Pull request by ax3l**
We already hack this option to read `numthreads = 1` already for benchmarks, thus we remove the confusing other values now.

https://github.com/ECP-WarpX/WarpX/blob/02726b58fa688ab321cc6da7ead30e79dca1cf60/Regression/prepare_file_ci.py#L80

### CODE REVIEW

**Comment by lgiacome** [comment]
For the future maybe it would be good to have at least some tests with multithreading in order to catch possible race conditions (?)

**Review by lgiacome — APPROVED** [review]

**Comment by ax3l** [comment]
> For the future maybe it would be good to have at least some tests with multithreading in order to catch possible race conditions (?)

Yes, I think the script "pre-processing" from `prepare_file_ci.py` should be reduced to a bare minimum (or perform only verification) and then setting this again in the `.ini` config files would work to test this.

**Comment by RemiLehe** [comment]
Thanks. Could you remove `text = re.sub( 'numthreads = \d+', 'numthreads = 1', text) ` as part of this PR?

**Comment by ax3l** [comment]
Thanks, good idea. Removed.

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
