### PR TITLE
3D performance tests: CI smaller

### PR DESCRIPTION
**Pull request by ax3l**
Reduce CI runtime, which currently was 40sec.

### CODE REVIEW

**Review by EZoni — COMMENTED** [review]
Thank you, Axel! This looks good, but I noticed that we didn't need to reset the checksum benchmarks. That's odd and the reason is that we actually do not run the default regression analysis on these tests, so the benchmarks do not exist. I think we should run the default regression analysis on these tests, too. Would you be OK with adding `analysisRoutine = Examples/analysis_default_regression.py` to each of these entries, and then adding the corresponding JSON files for the checksum benchmarks? Or were they missing on purpose for some reasons I'm not aware of?

**Comment by ax3l** [comment]
On those tests, I would not run these.

The reason for that is that these "Performance" tests are just making sure that the inputs syntax for https://github.com/ECP-WarpX/regression_testing does not break. All but one also don't even create output.

**Comment by EZoni** [comment]
@ax3l Thanks, I see. Then, a follow-up question: is there a reason why we are not reducing the grid size also for the tests `Performance_works_4_labdiags_2ppc` and `Performance_works_6_output_2ppc`? Is it because these two are already fast enough?

**Comment by ax3l** [comment]
Yes, turns out they only ran a few seconds because they have less particles per cell :)

**Review by EZoni — APPROVED** [review]
Thanks for answering my questions! Looks good to me.

**Pull request merged**
